version: "3.9"

services:
  the-one-gateway:
    build: ./java/api-gateway
    container_name: the-one-gateway
    ports:
      - "8080:8080"
    networks:
      - the-one-network
  the-one-discovery:
    build: ./java/service-discovery
    container_name: the-one-discovery
    ports:
      - "8081:8081"
    networks:
      - the-one-network

  the-one-user-service:
    build: ./java/users-service
    container_name: the-one-user-service
    ports:
      - "8083:8083"
    networks:
      - the-one-network

  the-one-user-db:
    image: mysql:5.7
    container_name: the-one-user-db
    environment:
      MYSQL_ROOT_PASSWORD: user_db_password
      MYSQL_DATABASE: user_db
      MYSQL_USER: user_service
      MYSQL_PASSWORD: user_service_pass
    ports:
      - "6033:3306"
    volumes:
      - ./databases/user-database/data-dump/volume:/var/lib/mysql
    networks:
      - the-one-network

#  the-one-outpost-db:
#    image: mysql:5.7
#    container_name: the-one-outpost-db
#    environment:
#      MYSQL_ROOT_PASSWORD: outpost_db_password
#      MYSQL_DATABASE: outpost_db
#      MYSQL_USER: outpost_service
#      MYSQL_PASSWORD: outpost_service_pass
#    ports:
#      - "6034:3306"
#    volumes:
#      - ./databases/outpost-database/data-dump/volume:/var/lib/mysql

networks:
  the-one-network:
    driver: bridge
